FROM tiangolo/node-frontend:10 as build-stage

ADD package*.json /app/
WORKDIR /app
RUN npm install

COPY . /app

RUN npm run build

FROM nginx:1.15

COPY --from=build-stage /app/build/ /usr/share/nginx/html
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf