# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
pipelines:
  default:
    - step:
        name: Build and test python
        image: python:3.6.5
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r backend/requirements.txt
          - python backend/manage.py test  
    - step:
        name: Build and test node
        image: node:8.5.0
        caches:
          - frontend-node
        script:
          - cd frontend/
          - npm install
          - npm test
definitions:
  caches:
    frontend-node: frontend/node_modules