version: '3'

services:
  redis:
    image: redis
  backend_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: triplar/backend
    env_file:
      - ./backend/.env
    command: python3 /app/manage.py rqworker
    links:
      - redis
  backend_scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: triplar/backend
    env_file:
      - ./backend/.env
    command: python3 /app/manage.py rqscheduler
    depends_on:
      - backend_worker
    links:
      - redis
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: triplar/backend
    env_file:
      - ./backend/.env
    command: python3 /app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - backend_scheduler
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: triplar/frontend
    ports:
      - "80:80"
      - "443:443"
    links:
      - backend