version: '3'

services:
  redis:
    image: redis
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: triplar/backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.development
    command: npm start
    ports:
      - "8000:8000"
    links:
      - redis
  backend-worker:
    image: triplar/backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.development
    command: npm run worker-dev
    links:
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: triplar/frontend
    env_file:
        - ./frontend/.env
    ports:
      - "80:80"
      - "443:443"
    links:
      - backend
