version: '3'

services:
  mongo:
    image: mongo
  redis:
    image: redis
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: triplar/backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.development
    command: npm start
    ports:
      - "8000:8000"
    links:
      - redis
#      - mongo
  backend-worker:
    image: triplar/backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.development
    command: npm run worker-dev
    links:
      - redis
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: triplar/frontend
    volumes:
      - ./frontend:/app
    command: npm start
    ports:
      - "3000:3000"
    links:
      - backend