version: '3'

services:
  redis:
    image: redis
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: triplar/backend
    env_file:
      - ./backend/.env
    command: npm run serve
    ports:
      - "8000:8000"
    links:
      - redis
  backend-worker:
    image: triplar/backend
    env_file:
      - ./backend/.env
    command: npm run worker-prod
    links:
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_BACKEND_HOST=${REACT_APP_BACKEND_HOST}
    image: triplar/frontend
    env_file:
        - ./frontend/.env
    ports:
      - "80:80"
      - "443:443"
    links:
      - backend
