export const GET_TRIP_ITINERARIES_REQUEST = 'GET_TRIP_ITINERARIES_REQUEST';
export const GET_TRIP_ITINERARIES_SUCCESS = 'GET_TRIP_ITINERARIES_SUCCESS';
export const GET_TRIP_ITINERARIES_FAILURE = 'GET_TRIP_ITINERARIES_FAILURE';

export const GET_ITINERARY_DAY_ITEMS_REQUEST = 'GET_ITINERARY_DAY_ITEMS_REQUEST';
export const GET_ITINERARY_DAY_ITEMS_SUCCESS = 'GET_ITINERARY_DAY_ITEMS_SUCCESS';
export const GET_ITINERARY_DAY_ITEMS_FAILURE = 'GET_ITINERARY_DAY_ITEMS_FAILURE';

export const ADD_TRIP_LOCATION_REQUEST = 'ADD_TRIP_LOCATION_REQUEST';
export const ADD_TRIP_LOCATION_SUCCESS = 'ADD_TRIP_LOCATION_SUCCESS';
export const ADD_TRIP_LOCATION_FAILURE = 'ADD_TRIP_LOCATION_FAILURE';

export const DELETE_TRIP_LOCATION_REQUEST = 'DELETE_TRIP_LOCATION_REQUEST';
export const DELETE_TRIP_LOCATION_SUCCESS = 'DELETE_TRIP_LOCATION_SUCCESS';
export const DELETE_TRIP_LOCATION_FAILURE = 'DELETE_TRIP_LOCATION_FAILURE';

export const ADD_ITEM_TO_ITINERARY_DAY_REQUEST = 'ADD_ITEM_TO_ITINERARY_DAY_REQUEST';
export const ADD_ITEM_TO_ITINERARY_DAY_SUCCESS = 'ADD_ITEM_TO_ITINERARY_DAY_SUCCESS';
export const ADD_ITEM_TO_ITINERARY_DAY_FAILURE = 'ADD_ITEM_TO_ITINERARY_DAY_FAILURE';

export const REMOVE_ITEM_FROM_ITINERARY_DAY_REQUEST = 'REMOVE_ITEM_FROM_ITINERARY_DAY_REQUEST';
export const REMOVE_ITEM_FROM_ITINERARY_DAY_SUCCESS = 'REMOVE_ITEM_FROM_ITINERARY_DAY_SUCCESS';
export const REMOVE_ITEM_FROM_ITINERARY_DAY_FAILURE = 'REMOVE_ITEM_FROM_ITINERARY_DAY_FAILURE';


export function getTripItineraries(tripId) {return {type: GET_TRIP_ITINERARIES_REQUEST, tripId}}
export function getItineraryDayDetail(itineraryId, date) {return {type: GET_ITINERARY_DAY_ITEMS_REQUEST, itineraryId, date}}

export function addTripLocation(tripId, location) {return {type: ADD_TRIP_LOCATION_REQUEST, tripId, location}}
export function deleteTripLocation(locationId, tripId) {return {type: DELETE_TRIP_LOCATION_REQUEST, locationId, tripId}}

export function addItemToItineraryDay(itineraryId, placeId, day, position) {
    return {type: ADD_ITEM_TO_ITINERARY_DAY_REQUEST, itineraryId, placeId, day, position}
}

export function removeItemFromItineraryDay(itineraryId, placeId, day) {
    return {type: REMOVE_ITEM_FROM_ITINERARY_DAY_REQUEST, itineraryId, placeId, day}
}