# Generated by Django 2.0.5 on 2018-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelp_api_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
