# Generated by Django 2.0.5 on 2018-09-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplocationitem',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triplocationitem',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='triplocationitem',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
