# Generated by Django 2.0.5 on 2018-09-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20180921_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocationitem',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triplocationitem',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
