# Generated by Django 2.0.5 on 2018-09-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20180921_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocationitem',
            name='api_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itinerary_items', to='places.APIPlace'),
        ),
    ]
