# Generated by Django 2.0.5 on 2018-09-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20180922_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocationitem',
            name='api_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.APIPlace'),
        ),
    ]
