# Generated by Django 2.0.5 on 2018-09-22 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20180922_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplocationitem',
            name='end',
        ),
        migrations.RemoveField(
            model_name='triplocationitem',
            name='start',
        ),
        migrations.AddField(
            model_name='triplocationitem',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triplocationitem',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triplocationitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triplocationitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
